[build]
  command = "npm run build"
  publish = "dist"
  
# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirects for common paths
[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
